import tkinter as tk
import tkinter.filedialog as tkf

# if __name__ == "__main__":
root = tk.Tk()
root.title("Multithreading GUI")
menu = tk.Menu(root)
root.config(menu=menu)
Helpmenu = tk.Menu(menu)
menu.add_cascade(label="Help", menu=Helpmenu)
tk.Label(root, text="Stelle der Fibonaccizahl:").grid(row=0, column=0, sticky="w", padx=5)
e1 = tk.Entry(root)
e1.grid(row=0, column=1, sticky="w", padx=5)
tk.Label(root, text="Fibonaccizahl der Stelle X:").grid(row=1, column=0, sticky="w", padx=5)
tk.Label(root, text="Hier steht die Fibonaccizahl").grid(row=1, column=1, sticky="w", padx=5)
tk.Label(root, text="Liste Sortieren:").grid(row=2, column=0, sticky="w", padx=5)
tk.Label(root, text="Start Liste:").grid(row=3, column=0, sticky="w", padx=5)
e2 = tk.Entry(root)
e2.grid(row=3, column=1, sticky="w", padx=5)
tk.Label(root, text="EndeListe").grid(row=4, column=0, sticky="w", padx=5)
e3 = tk.Entry(root)
e3.grid(row=4, column=1, sticky="w", padx=5)
tk.Label(root, text="Zahlen in Liste, die durch n Teilbar sind: n=").grid(row=5, column=0, sticky="w", padx=5)
e4 = tk.Entry(root)
e4.grid(row=5, column=1, sticky="w", padx=5)
tk.Label(root, text="Ergebnis:").grid(row=6, column=0, sticky="w", padx=5)
tk.Label(root, text="Hier steht die Liste").grid(row=6, column=1, sticky="w", padx=5)
tk.Button(root, text="Quit", command=root.quit).grid(row=7, column=0, sticky="w", padx=5)
tk.Button(root, text="Berechnen").grid(row=7, column=0, sticky="ne", padx=5)
root.mainloop()